from .views import *
from .chefInformatiqueView import *
from .professeurView import *
from .principalView import *
from .parentView import *
from .eleveView import *
from .matiereView import *
from .moduleView import *
from .classeView import *
from .specialiteView import *
from .trimestreView import *
from .sequenceView import *
from .ajax import *
from .noteView import *
from .coefMatiereClasseView import *