# Generated by Django 3.1.7 on 2021-03-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
