# Generated by Django 3.1.7 on 2021-03-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Resultat', 'verbose_name_plural': 'Resultats'},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={},
        ),
        migrations.RemoveField(
            model_name='classe',
            name='eleve',
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleveClasse', to='gestionNote.classe'),
        ),
    ]
