# Generated by Django 3.1.7 on 2021-03-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0004_auto_20210317_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='coefficient_Matiere',
        ),
        migrations.CreateModel(
            name='Classe_matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient_Matiere', models.CharField(max_length=200, verbose_name='coefficient_Matiere')),
                ('classe_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionNote.classe', verbose_name='classe_m')),
                ('matiere_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionNote.matiere', verbose_name='matiere_c')),
            ],
        ),
    ]
