# Generated by Django 3.1.7 on 2021-03-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0005_auto_20210319_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='matiere',
        ),
        migrations.AddField(
            model_name='matiere',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matiereModule', to='gestionNote.modules'),
        ),
    ]
