# Generated by Django 3.1.7 on 2021-03-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0007_remove_modules_coefficient_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matiere', 'verbose_name_plural': 'Matieres'},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
