# Generated by Django 3.1.7 on 2021-03-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0008_auto_20210320_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='module',
        ),
        migrations.AddField(
            model_name='classe',
            name='module',
            field=models.ManyToManyField(related_name='moduleClasse', to='gestionNote.Modules'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau_classe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='niveau_classe'),
        ),
    ]
