# Generated by Django 3.1.7 on 2021-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0009_auto_20210320_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='nom_classe',
        ),
        migrations.AddField(
            model_name='classe',
            name='libelle_classe',
            field=models.CharField(default='libelle', max_length=200, verbose_name='libelle_classe'),
        ),
    ]
