# Generated by Django 3.1.7 on 2021-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0010_auto_20210320_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='classe',
        ),
        migrations.AddField(
            model_name='specialite',
            name='classe',
            field=models.ManyToManyField(related_name='classeSpec', to='gestionNote.Classe'),
        ),
    ]
