# Generated by Django 3.1.7 on 2021-03-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0012_note_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='type_note',
        ),
    ]
