# Generated by Django 3.1.7 on 2021-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0013_remove_note_type_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='classeM',
            field=models.ManyToManyField(related_name='classeMatiere', to='gestionNote.Classe'),
        ),
    ]
