# Generated by Django 3.1.7 on 2021-03-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0014_matiere_classem'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='classe_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classeNote', to='gestionNote.classe'),
        ),
    ]
