# Generated by Django 3.1.7 on 2021-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0016_auto_20210330_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sexe'),
        ),
    ]
