# Generated by Django 3.1.7 on 2021-04-02 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNote', '0017_auto_20210330_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe_matiere',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe_matiere',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classe_matiere',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
